services:
  back_end:
    build: ./back-end
    container_name: back-end
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/app
      - /app/node_modules

  front-end:
    build: ./front-end/src
    container_name: front-end
    ports:
      - "3001:3001"
    env_file:
      - ./front-end/src/.env
    volumes:
      - ./front-end/src:/app
      - /app/node_modules